### ISSUE TITLE
undefined method `host_keys' for #<EventMachine::Ssh::Connection:...>

### ISSUE THREAD

**Issue by sergeych** [gruis/em-ssh#30]
`EM::Ssh.start('sergeych.net', 'sergeych', password: '123123') { |connection| p 'start' }`

:(

**Comment by kt97679** [comment]
I'm using following workaround:
<pre>
module EventMachine
    class Ssh
        class Connection < EventMachine::Connection
            def host_keys
                return []
            end
        end
    end
end
</pre>
It works for me but I'm not sure if this provides correct fix for the issue.

**Comment by kt97679** [comment]
This should be fixed in 0.8.0
